### ISSUE TITLE
Update to FairBid SDK 3.4.0

### ISSUE THREAD

**Issue by andre-arsenault** [ukasz123/fairbid_flutter#10]
Hello!

Today I will be updating this package to use SDK 3.4.0 which was just released. Instead of sending the pull request to the `release/0.8.0-dev.4` branch, would you prefer that I sent it to `master` and then you can also merge it into `0.8.0-dev.4`? This would make the update availble for any users who aren't on the dev branch.

I will also update the example app to use the latest mediated network SDKs supported by 3.4.0.

**Comment by ukasz123** [comment]
I am going to prepare update myself. This version allows for some simpler code for native banner views (as there would be only two supported heights). Also I'm removing not supported banner `rectangle` format. This is already in WIP and should be ready today (tomorrow morning).
Example is also being updated.

**Comment by andre-arsenault** [comment]
Even better. That's great, thank you!

**Comment by ukasz123** [comment]
@andre-arsenault Apparently the version 3.4.0 has some critical issues and the release was reverted. I'll update the dependencies as soon as the patch will be released.
